source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'
pod 'AMWaveTransition'
pod "AYVibrantButton"
pod 'SZTextView'
pod 'AVOSCloud'
pod 'AVOSCloudCrashReporting'
pod 'LeanCloudFeedback'
pod 'CRToast', '~> 0.0.7'
pod 'JSONModel'
pod 'Masonry'
pod 'TSMessages'
pod 'VBFPopFlatButton'
pod 'FlatUIKit'
pod 'JNKeychain'
pod 'HMSegmentedControl'
pod 'SDWebImage', '~>3.7'
pod 'PureLayout'
pod 'UIActivityIndicator-for-SDWebImage'
