source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'
pod "AYVibrantButton"
pod 'AVOSCloud'
pod 'AVOSCloudCrashReporting'
pod 'LeanCloudFeedback'
pod 'JSONModel'
pod 'Masonry'
pod 'JNKeychain'
pod 'SDWebImage', '~>3.7'
pod 'KGModal', '~> 0.0.1'
pod 'ActionSheetPicker-3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'JGProgressHUD'
pod 'MJRefresh'
pod 'WYPopoverController'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'